name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the following information to help us investigate.
        
        **Note**: This is a personal project maintained on a best-effort basis. Response times may vary.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the issue
      placeholder: |
        1. Use method X with parameters Y
        2. Call method Z
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that demonstrates the issue
      render: csharp
      placeholder: |
        var result = "test".SomeMethod();
        // Expected: X, Got: Y

  - type: input
    id: version
    attributes:
      label: Library Version
      description: Which version of Eventualist.Extensions are you using?
      placeholder: e.g., 5.0.0.1
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Which version of .NET are you using?
      placeholder: e.g., .NET 10.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: e.g., Windows 11, macOS 14, Ubuntu 22.04
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (stack traces, logs, etc.)
      placeholder: Any additional information that might help

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am using a supported version (5.x)
          required: false
        - label: I have provided a minimal code sample that reproduces the issue
          required: false
