name: Question
description: Ask a question about using the library
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!
        
        **Note**: This is a personal project maintained on a best-effort basis. Response times may vary.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or what you've tried so far
      placeholder: I'm trying to... I've already tried...

  - type: textarea
    id: code
    attributes:
      label: Code Sample (if applicable)
      description: Share relevant code if it helps explain your question
      render: csharp
      placeholder: |
        // Your code here

  - type: input
    id: version
    attributes:
      label: Library Version
      description: Which version of Eventualist.Extensions are you using?
      placeholder: e.g., 5.0.0.1

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked the README and documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
